---
- name: 'Ensure _user_deployment_users.groups are defined properly'
  ansible.builtin.assert:
    that:
      # _group.name
      - '_group.name is defined'
      - '_group.name is string'
      - '_group.name != None'
      - "_group.name != ''"

      # _group.gid
      - >-
          (_group.gid is defined) | ternary(_group.gid | default(None) | int | string
          == _group.gid | default(None) | string, true)
      - '(_group.gid is defined) | ternary(_group.gid | default(None) is number, true)'
      - '(_group.gid is defined) | ternary(_group.gid | default(None) is integer, true)'
      - '(_group.gid is defined) | ternary(_group.gid | default(None) >= 1, true)'
    success_msg: 'Groups are defined correctly'
    fail_msg: 'One or more groups failed to validated correctly'
    quiet: '{{ _user_deployment_quiet_assert }}'
  loop: '{{ _user.groups }}'
  loop_control:
    loop_var: '_group'
...
